//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkPointChecker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentPoints
    {
        public System.Guid Id { get; set; }
        public string Adress { get; set; }
        public string GLN { get; set; }
        public string Customer { get; set; }
    }
}
